services:
  postgres:
    image: postgres:16-alpine
    container_name: file_storage_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: file_storage_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d file_storage_system"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:4.2.5-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Cổng kết nối App
      - "15672:15672" # Cổng giao diện quản lý (Web UI)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#    deploy:
#      resources:
#        limits:
#          memory: 1gb # Giới hạn cứng RAM cho RabbitMQ container
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  minio:
    image: minio/minio:latest
    container_name:  minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p local/file-storage;
      /usr/bin/mc anonymous set none local/file-storage;
      exit 0;
      "
    restart: "no"

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  minio_data:
