spring:
  application:
    name: file_storage_system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/file_storage_system}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

app:
  security:
    system-admin-bootstrap-secret: ${SYSTEM_ADMIN_BOOTSTRAP_SECRET:DatDQ225275}
    jwt-secret: ${JWT_SECRET:y9Gb2ECXRGJ14GeyJfAUHM9F/N8fXkp/Qz3C17pqTc4=}
    jwt-access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
    jwt-refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:2592000000}
    refresh-cookie-name: ${REFRESH_COOKIE_NAME:refresh_token}
    refresh-cookie-secure: ${REFRESH_COOKIE_SECURE:false}
    refresh-cookie-same-site: ${REFRESH_COOKIE_SAME_SITE:Lax}

